# Model debugging

Debug file. Use `model.py` to load the actual model architecture

In [1]:
import torch
import torch.nn as nn
from torchvision import models

In [22]:
%run model.py

In [23]:
model = ResnetBasedModel(n_features=2048, transition_conv=True)

In [24]:
n_samples = 4
image_channels = 3
image_width = 512
image_height = 512

image = torch.Tensor(n_samples, image_channels, image_height, image_width)
y, embeddings, activations = model(image)

y.size()

Activations:  torch.Size([4, 14, 16, 16])


torch.Size([4, 14])

In [13]:
a = torch.randn(3, 2)
a

tensor([[ 0.7013,  0.3511],
        [ 0.2651,  0.3893],
        [ 0.4031, -1.2247]])

In [14]:
b = a
b

tensor([[ 0.7013,  0.3511],
        [ 0.2651,  0.3893],
        [ 0.4031, -1.2247]])

In [20]:
b = a.view(6)
b

tensor([ 0.7013,  0.3511,  0.2651,  0.3893,  0.4031, -1.2247])

In [21]:
a

tensor([[ 0.7013,  0.3511],
        [ 0.2651,  0.3893],
        [ 0.4031, -1.2247]])

In [31]:
a = torch.Tensor(4, 2048).to("cuda")
b = torch.Tensor(3, 2048).to("cuda")
a.size(), b.size()

(torch.Size([4, 2048]), torch.Size([3, 2048]))

In [35]:
torch.cat([a, b], out=a)
a.size()

torch.Size([10, 2048])

In [37]:
b

tensor([[2.9676e-26, 4.5870e-41, 2.9676e-26,  ..., 1.4187e+13, 4.5441e+30,
         9.6828e+05],
        [3.3949e-09, 1.5434e+25, 3.1554e+03,  ..., 2.6908e+20, 1.8464e+25,
         1.4987e+10],
        [1.2778e+19, 1.2922e+19, 1.7636e+25,  ..., 5.1696e+07, 3.1550e+03,
         3.4468e+27]], device='cuda:0')